version: '2'

services:
  klipper:
    image: dimalo/klipper-moonraker
      #build:
      #dockerfile: ./klipper/Dockerfile
      #context: .
    # if klipper cannot connect to the printer check permissions on rpi then add the group here
    # group_add:
    #   - "996"
    #   - "998"
    cap_add:
      - SYS_NICE
    container_name: klipper
    ports:
      - 7125:7125
    restart: unless-stopped
    volumes:
      #- gcode_files:/home/klippy/gcode_files
      # be aware to create your own branch if you mount the config folder as it will be updated on the main branch
      # that way you can merge upstream changes to your customized configs
      - ./config:/home/klippy/.config
      #- moonraker_data:/home/klippy/.moonraker_database
      # - <<your_config_path>>:/home/klippy/.config
      - ./config/printer.cfg:/home/klippy/.config/printer.cfg
      - '/run/udev:/run/udev:ro'
      - '/dev:/dev'
      - '/tmp:/tmp-host'
    privileged: true


  fluidd:
    image: cadriel/fluidd
      #build:
      #dockerfile: Dockerfile
      #context: frontend
      #network: host
    restart: unless-stopped
    container_name: fluidd
    ports:
      - 8010:80
    depends_on: 
      - klipper
      # - klipper_another_printer
    links:
      - klipper:klipper
      # - klipper_another_printer:klipper_another_printer

  # mainsail:
  #   image: dimalo/mainsail
  #   build:
  #     dockerfile: Dockerfile
  #     context: frontend
  #     args:
  #       FRONTEND_ZIP_URL: https://github.com/meteyou/mainsail/releases/latest/download/mainsail.zip
  #   container_name: mainsail
  #   ports:
  #     - 8011:80
  #   depends_on: 
  #     - klipper
  #     # - klipper_another_printer
  #   links:
  #     - klipper:klipper
  #     # - klipper_another_printer:klipper_another_printer

volumes: 
  gcode_files:
  moonraker_data:

